# THIS IS THE BLOG TUTORIAL
# https://github.com/skills/github-pages
#
title: iago.zip

description: >- 
  Ⓒ 2023  Iago Moreira
baseurl: "" 
domain: "www.iago.zip"
url: "https://www.iago.zip"
twitter_username: morallito
github_username:  morallito
linkedin_username: iagohmoreira

theme: minima

github:
  github_url: github.com/morallito

show_downloads: false
google_analytics: 

analytics:
  provider: "google-gtag"
  google:
    tracking_id: "G-T5M8RFB87S"
    anonymize_ip: false # default

