# THIS IS THE BLOG TUTORIAL
# https://github.com/skills/github-pages
#
title: Iago's notebook
email: iagohenrique22@hotmail.cm
description: >- 
  Hey, welcome to Iago's notebook. I use this as a repo, to store links, docs, and other 
  things that I am currently studying.

baseurl: "" 
domain: "www.iago.zip"
url: "https://www.iago.zip"
twitter_username: morallito
github_username:  morallito

theme: minima

github:
  github_url: github.com/morallito

show_downloads: false
google_analytics: G-T5M8RFB87S


